피드관리 기능 개선
f-lab-edu/Pale-Blue-Dot pull request #10
Opened 2024-02-20 14:44 UTC by luke-jeong

모어방식을 적용한 조회기능을 추가했고, 피드 레퍼지토리커스텀을 생성해서 적용했습니다

2024-02-23 16:40 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요 ~

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/controller/CommentController.java
> +    @PostMapping("")
"" 없어도 될거같아요 ~

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/controller/CommentController.java
> +                              @PathVariable Long feedId,
여기 엔드포인트에 PathVariable이 없는 것 같아요 ?

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/controller/FeedController.java
> +    public void createFeed(@RequestBody @Valid FeedCreate request, @PathVariable String memberName){
여기도 PathVariable은 없는 것 같습니다 ~ 그리고 혹시 memberId에서 memberName으로 바꾸신 이유가 있을까요 ?

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/controller/FeedController.java
> +    public List<Feed> getMyFeeds(@RequestParam int size, String memberName){
여기는 PathVariable이 붙어야될 것 같은데요 ?

혹시 작업 후 서버 수행해서 api 요청 확인 해보셨을까요 ~?

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/domain/Comment.java
> +    @CreatedDate
이거 Audit 리스너 안달려있어서 작동 안되지않나요 ?

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/repository/FeedRepositoryImpl.java
> +    public List<Feed> getAllFeeds(int size){
getAllFeeds 라고 하면 전체 데이터를 가져오는것 처럼 보일 것 같아요 findMoreFeeds 정도로 네이밍 해주면 어떨까요 ?

그리고 size만 받으면 늘 똑같은 위치부터 시작할 것 같은데, 원하신 동작이 맞을까요 ?

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/request/CommentCreate.java
> +@Setter
Setter를 지양하는 이유를 한번 찾아보시면 좋을 것 같아요 ~

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/service/CommentService.java
> +@Transactional
개인적으로 `@Transactional` 은 클래스 단위로 지정되어있으면 잘 안보여서 메서드에 지정하는게 좋다고 생각합니다

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/service/CommentService.java
> +        Comment comment = Comment.builder()
Request에서 Entity 만들어주는 메서드를 제공해주면 어떨까요 ?

2024-02-23 16:40 UTC, f-lab-moony commented on src/main/java/com/luke/palebluedot/service/FeedService.java
> +        Optional<Feed> searchFeed = feedRepository.findById(feedId);
Optional에는 orElseThrow 라는 메서드가 있어요

2024-02-23 16:40 UTC, f-lab-moony commented on src/test/groovy/com/luke/palebluedot/ServiceTest/FeedServiceTest.groovy
> +        feedService = new FeedService(feedRepository, memberRepository)
이거 굳이 셋업에서 안해도 될 것 같아요

2024-03-02 06:05 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/controller/CommentController.java
> +    @PostMapping("")
넵 알겠습니다

2024-03-02 06:08 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/controller/FeedController.java
> +    public void createFeed(@RequestBody @Valid FeedCreate request, @PathVariable String memberName){
현재 member entity에서 사용중인 memberId는 Long 타입으로, 작성글에 저장되는 member 정보는 실제 사용자 id가 저장되는 string 타입의 memberName가 들어가는게 맞다고 생각했습니다.

2024-03-02 06:10 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/controller/FeedController.java
> +    public List<Feed> getMyFeeds(@RequestParam int size, String memberName){
수정중이었는데 미처 커밋되지 않은것 같습니다

2024-03-02 06:13 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/domain/Comment.java
> +    @CreatedDate
createdate, updatedate는 미처 테스트 못해봐서 몰랐네요. 수정하겠습니다

2024-03-02 06:14 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/request/CommentCreate.java
> +@Setter
네 찾아보고 수정하겠습니다

2024-03-02 06:41 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/repository/FeedRepositoryImpl.java
> +    public List<Feed> getAllFeeds(int size){
확인해서 수정할게요

2024-03-02 06:42 UTC, luke-jeong commented on src/main/java/com/luke/palebluedot/service/CommentService.java
> +@Transactional
넵 @Transactional에 대해서도 다시 한번 공부해보겠습니다

2024-03-06 14:10 UTC, closed without merging